version: "{build}"
clone_depth: 1
image: Ubuntu2004

build_script:
- sh: sudo update-alternatives --set gcc /usr/bin/gcc-9
- sh: ggbuild/lua.linux make.lua release > build.ninja
- sh: ggbuild/ninja.linux -v -k 0
- sh: ggbuild/lua.linux ggbuild/ninja_timeline.lua

test_script:
- sh: tests/test_downloads.sh

artifacts:
- path: release
  name: cocaine_diesel_linux
