version: "{build}"
clone_depth: 1
image: Visual Studio 2022

build_script:
- cmd: call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat" amd64
- cmd: ggbuild\lua.exe make.lua release > build.ninja
- cmd: ggbuild\ninja.exe -v -k 0
- cmd: ggbuild\lua.exe ggbuild\ninja_timeline.lua
- cmd: ggbuild\ducible.exe release\client.exe
- cmd: ggbuild\ducible.exe release\server.exe
- cmd: ggbuild\ducible.exe release\bc4.exe
- cmd: ggbuild\ducible.exe release\dieselmap.exe

artifacts:
- path: release
  name: cocaine_diesel_windows
